name: 'F´ Project Builder Action'
description: 'Build and Test F´ Projects in CI'
author: 'F´'

inputs:
  build_location:
    description: "The location to build in. E.g. MyDeployment/"
    required: true
  run_unit_tests:
    description: "Whether to run Unit Tests"
    required: false
    default: "true"
  fprime_version:
    required: false
    description: "F´ version to use. Defaults to project submodule version."
    default: ""
  fprime_location:
    required: false
    description: "Relative path from project root to F´ submodule"
    default: "./fprime"
  post_script:
    required: false
    description: "Optional script to run after build"
    default: ""

runs:
  using: "composite"
  steps:
    - if: ${{ inputs.fprime_version }} != ""
      run: |
        cd ${{ inputs.fprime_location }}
        git checkout ${{ inputs.fprime_version }}
      shell: bash
    - run: |
        pip3 install -r ${{ inputs.fprime_location }}/requirements.txt
      shell: bash
    - working-directory: ${{ inputs.build_location }}
      run: |
        fprime-util generate
        fprime-util build
      shell: bash
    - if: ${{ inputs.run_unit_tests }} == "true"
      working-directory: ${{ inputs.build_location }}
      run: |
        fprime-util generate --ut
        fprime-util build --ut
        fprime-util check
      shell: bash
    - if: ${{ inputs.post_script }} != ""
      run: ./${{ inputs.post_script }} 
      shell: bash

