name: 'F´ Project Builder Action'
description: 'Build and Test F´ Projects in CI'
author: 'F´'

inputs:
  build_location:
    description: "Path to F´ module to build. E.g. MyDeployment/"
    required: true
  fprime_version:
    required: false
    description: "F´ version to use. Defaults to project submodule version."
    default: ""
  fprime_location:
    required: false
    description: "Relative path from project root to F´ submodule"
    default: "./fprime"
  run_unit_tests:
    description: "Run a Unit Test build (--ut) instead of a normal build [true|false] (default: false)"
    required: false
    default: "false"
  skip_requirements_install:
    description: "Skip installing requirements.txt [true|false] (default: false)"
    required: false
    default: "false"
  target_platform:
    description: "F´ build platform (e.g. Linux, Darwin). Default specified in settings.ini."
    required: false
    default: ""
  extra_generate_args:
    description: "Extra arguments to pass to fprime-util generate"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - if: inputs.fprime_version != ''
      run: |
        cd ${{ inputs.fprime_location }}
        git checkout ${{ inputs.fprime_version }}
      shell: bash
    - if: inputs.skip_requirements_install == 'false'
      run: |
        pip3 install -r ${{ inputs.fprime_location }}/requirements.txt
      shell: bash
    - if: inputs.run_unit_tests == 'false'
      working-directory: ${{ inputs.build_location }}
      run: |
        fprime-util generate ${{ inputs.extra_generate_args }} ${{ inputs.target_platform }}
        fprime-util build ${{ inputs.target_platform }}
      shell: bash
    - if: inputs.run_unit_tests == 'true'
      working-directory: ${{ inputs.build_location }}
      run: |
        fprime-util generate --ut ${{ inputs.extra_generate_args }}
        fprime-util build --ut
        fprime-util check
      shell: bash

