name: 'F´ Project Builder Reusable Workflow'

on:
  workflow_call:
    inputs:
      build_location:
        description: "The location to build in. E.g. MyDeployment/"
        type: string
        required: true
      run_unit_tests:
        description: "Whether to run Unit Tests"
        type: boolean
        required: false
        default: true
      fprime_version:
        required: false
        type: string
        description: "F´ version to use. Defaults to project submodule version."
        default: ""
      fprime_location:
        required: false
        type: string
        description: "Relative path from project root to F´ submodule"
        default: "./fprime"
      post_script:
          required: false
          type: string
          description: "Optional script to run after build"
          default: ""

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build F´ Project"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - if: ${{ inputs.fprime_version }} != ""
        name: "Checkout F´ Version"
        run: |
          cd ${{ inputs.fprime_location }}
          git checkout ${{ inputs.fprime_version }}
        shell: bash
      - name: "Install requirements.txt"
        run: |
          pip3 install -r ${{ inputs.fprime_location }}/requirements.txt
        shell: bash
      - name: "Build Project"
        working-directory: ${{ inputs.build_location }}
        run: |
          fprime-util generate
          fprime-util build
        shell: bash
      - if: ${{ inputs.post_script }} != ""
        name: "Run Post Script"
        run: ./${{ inputs.post_script }}
        shell: bash

  runUT:
    if: ${{ inputs.run_unit_tests }} == "true"
    runs-on: ubuntu-latest
    name: "Run Unit Tests"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - if: ${{ inputs.fprime_version }} != ""
        name: "Checkout F´ Version"
        run: |
          cd ${{ inputs.fprime_location }}
          git checkout ${{ inputs.fprime_version }}
        shell: bash
      - name: "Install requirements.txt"
        run: |
          pip3 install -r ${{ inputs.fprime_location }}/requirements.txt
        shell: bash
      - name: "Buld and Run Unit Tests"
        working-directory: ${{ inputs.build_location }}
        run: |
          fprime-util generate --ut
          fprime-util build --ut
          fprime-util check
        shell: bash

